### ISSUE TITLE
Crashing when opening "Editors"

### ISSUE THREAD

**Issue by trevynmace** [adituv/gsmagic#1]
I'm really excited about this tool but can't get it to work! When opening "Editors" using a Golden Sun rom (not TLA) it will crash with this error:
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=gsmagic
  StackTrace:
   at gsmagic.Bits.getInt32(Byte[] buffer, Int32 pos) in C:\Users\trevyn\git\gsmagic\!Static\Bits.cs:line 56
   at gsmagic.Comp.decompText(Byte[] src) in C:\Users\trevyn\git\gsmagic\!Static\Comp.cs:line 374
   at gsmagic.Editors.Editors_Load(Object sender, EventArgs e) in C:\Users\trevyn\git\gsmagic\Editors.cs:line 25
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I pulled down the code and I'm trying to run it locally, and it crashes at the same line for the same reason.
It's trying to get a position on the buffer that's out of bounds because the buffer isn't long enough.

for reference:
buffer = byte[8388608], pos = 1532470256

Would love any help! :)

**Comment by adituv** [comment]
Sorry, I don't think I can really help.  This was always a mirror of the code for Teawater's program; I was planning to fix the bugs and implement missing features but ended up moving away from Golden Sun.  I'd suggest getting in contact with him if possible; he is Fox on the GSHC forums - http://forum.goldensunhacking.net
